name: XQORA Local CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make deployment script executable
        run: chmod +x automation/scripts/deploy.sh

      - name: Deploy application locally
        run: ./automation/scripts/deploy.sh
